sudo: false

language: perl
perl:
  - "perl-5.25.10"

before_install:
  - if perlbrew list | grep 5.25.10 >/dev/null; then true; else perlbrew install --notest 5.25.10; fi
  - perlbrew switch 5.25.10
  - rvm install 2.3.0
  - gem install bundler -v 1.14.6
  - bundle install

script: bundle exec rake

cache:
  bundler: true
  directories:
    - ~/perl5
    - ~/.rvm
